Repository Gongju-Unity-Bootcamp/DirectionAR, pull requests merged in 2024-03, with the labels that each got.

#15 bug: EventSystem 중복 발생
  DirectionAR/Assets/Scripts/Scene/BaseScene.cs
Labels: bug

#17 feat: 새로 추가 및 수정된 Prefab Button Mapping
  DirectionAR/Assets/Resources/Prefabs/ARZoneMenu.prefab
  DirectionAR/Assets/Resources/Prefabs/LoadingUI.prefab
  DirectionAR/Assets/Resources/Prefabs/Navigation.prefab
  DirectionAR/Assets/Resources/Prefabs/Navigation.prefab.meta
  DirectionAR/Assets/Resources/Prefabs/Street.prefab
  DirectionAR/Assets/Resources/Prefabs/Street.prefab.meta
  DirectionAR/Assets/Scenes/Awake.unity
  DirectionAR/Assets/Scripts/Manager/UIManager.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneButton.cs.meta
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_FooterButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_HeaderButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_MainButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_NavButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_NavButton.cs.meta
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_StreetButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_StreetButton.cs.meta
Labels: enhancement

#18 bug: Build 오류
  DirectionAR/ProjectSettings/ProjectSettings.asset
Labels: bug

#24 feat: ARZone Popup
  DirectionAR/Assets/Resources/Images/Direction 1.png
  DirectionAR/Assets/Resources/Images/Direction 1.png.meta
  DirectionAR/Assets/Resources/Images/Popup/IMG_ConsentBG.png
  DirectionAR/Assets/Resources/Images/Popup/IMG_ConsentBG.png.meta
  DirectionAR/Assets/Resources/Prefabs/ARZoneInfo.prefab
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneInfoButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneInfoButton.cs.meta
Labels: enhancement

#28 feat: ARZoneMenu prefab 내에 ARZoneButton 생성 및 배치
  DirectionAR/Assets/Resources/ARData.meta
  DirectionAR/Assets/Resources/ARData/Item1.asset
  DirectionAR/Assets/Resources/ARData/Item1.asset.meta
  DirectionAR/Assets/Resources/ARData/Item2.asset
  DirectionAR/Assets/Resources/ARData/Item2.asset.meta
  DirectionAR/Assets/Resources/Prefabs/ARZoneButton.prefab
  DirectionAR/Assets/Resources/Prefabs/ARZoneButton.prefab.meta
  DirectionAR/Assets/Resources/Prefabs/ARZoneMenu.prefab
  DirectionAR/Assets/Scripts/AR.meta
  DirectionAR/Assets/Scripts/AR/ARMenuManager.cs
  DirectionAR/Assets/Scripts/AR/ARMenuManager.cs.meta
  DirectionAR/Assets/Scripts/AR/Item.cs
  DirectionAR/Assets/Scripts/AR/Item.cs.meta
  DirectionAR/Assets/Scripts/Manager/Managers.cs
  DirectionAR/Assets/Scripts/Manager/ResourceManager.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARPickButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARPickButton.cs.meta
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_FooterButton.cs
  DirectionAR/Assets/Scripts/UI/UI_Base.cs
  DirectionAR/Assets/Scripts/Utils/Path.cs
Labels: enhancement

#36 bug: 뒤로가기 버튼 버그
  DirectionAR/Assets/Scripts/Scene/MainScene.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARBackButton.cs
Labels: bug

#38 bug: GPS 권한 오류
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ConsentGPSButton.cs
Labels: bug

#40 chore: ETC
  DirectionAR/Assets/Plugins/Android/AndroidManifest.xml
  DirectionAR/Assets/Plugins/Android/proguard-user.txt
  DirectionAR/Assets/Resources/Images/ARZone/Button_Back.png
  DirectionAR/Assets/Resources/Images/ARZone/Button_Back.png.meta
  DirectionAR/Assets/Resources/Images/ARZone/Button_BackHover.png
  DirectionAR/Assets/Resources/Images/ARZone/Button_BackHover.png.meta
  DirectionAR/Assets/Scenes/ARCamera.unity
Labels: wontfix

#42 feat: Android Manager 생성
  DirectionAR/Assets/Scripts/Manager/ARMenuManager.cs
  DirectionAR/Assets/Scripts/Manager/ARMenuManager.cs.meta
  DirectionAR/Assets/Scripts/Manager/AndroidManager.cs
  DirectionAR/Assets/Scripts/Manager/AndroidManager.cs.meta
  DirectionAR/Assets/Scripts/Manager/Managers.cs
  DirectionAR/Assets/Scripts/Manager/ResourceManager.cs
  DirectionAR/Assets/Scripts/Manager/UIManager.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ARZoneButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ConsentCameraButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_ConsentGPSButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_FooterButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_HeaderButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_MainButton.cs
Labels: enhancement

#44 feat : NAVER STATIC MAP과 GPS 연동
  DirectionAR/Assets/Plugins/Android/proguard-user.txt
  DirectionAR/Assets/Scenes/ARNavigation.unity
  DirectionAR/Assets/Scenes/ARNavigation.unity.meta
  DirectionAR/Assets/Scripts/Gps.meta
  DirectionAR/Assets/Scripts/Gps/GpsManager.cs
  DirectionAR/Assets/Scripts/Gps/GpsManager.cs.meta
  DirectionAR/Assets/Scripts/Gps/NStaticMapManager.cs
  DirectionAR/Assets/Scripts/Gps/NStaticMapManager.cs.meta
  DirectionAR/ProjectSettings/EditorBuildSettings.asset
  DirectionAR/ProjectSettings/ProjectSettings.asset
Labels: documentation

#46 feat: 스크립트 개선 및 통합
  DirectionAR/Assets/Scenes/ARNavigation.unity
  DirectionAR/Assets/Scripts/Gps/NStaticMapManager.cs
  DirectionAR/Assets/Scripts/Manager/AndroidManager.cs
  DirectionAR/Assets/Scripts/Manager/GpsManager.cs
  DirectionAR/Assets/Scripts/Manager/GpsManager.cs.meta
  DirectionAR/Assets/Scripts/Manager/NStaticMapManager.cs
  DirectionAR/Assets/Scripts/Manager/NStaticMapManager.cs.meta
  DirectionAR/Assets/Scripts/Scene/ARNavigationScene.cs
  DirectionAR/Assets/Scripts/Scene/ARNavigationScene.cs.meta
  DirectionAR/Assets/Scripts/Utils/Define.cs
Labels: enhancement

#52 feat : 길찾기 bing Maps SDK 전환
  DirectionAR/Assets/MapsURP.meta
  DirectionAR/Assets/MapsURP/ClippingVolume.cginc
  DirectionAR/Assets/MapsURP/ClippingVolume.cginc.meta
  DirectionAR/Assets/MapsURP/ContourLines.cginc
  DirectionAR/Assets/MapsURP/ContourLines.cginc.meta
  DirectionAR/Assets/MapsURP/ElevationOffset.cginc
  DirectionAR/Assets/MapsURP/ElevationOffset.cginc.meta
  DirectionAR/Assets/MapsURP/MapsURPTerrain.mat
  DirectionAR/Assets/MapsURP/MapsURPTerrain.mat.meta
  DirectionAR/Assets/MapsURP/UnlitMapsSDKTerrain.shader
  DirectionAR/Assets/MapsURP/UnlitMapsSDKTerrain.shader.meta
  DirectionAR/Assets/Plugins/Android/proguard-user.txt
  DirectionAR/Assets/Resources/Images/Navigation/MapIcon/Icon_PublicPlace.png.meta
  DirectionAR/Assets/Resources/Prefabs/Icon_PublicPlace.png
  DirectionAR/Assets/Resources/Prefabs/Icon_PublicPlace.png.meta
  DirectionAR/Assets/Resources/Prefabs/MapPin.prefab
  DirectionAR/Assets/Resources/Prefabs/MapPin.prefab.meta
  DirectionAR/Assets/Resources/Prefabs/Navigation.prefab
  DirectionAR/Assets/Scenes/Main.unity
  DirectionAR/Assets/Scenes/Navigation.unity
  DirectionAR/Assets/Scenes/Navigation.unity.meta
  DirectionAR/Assets/Scripts/2DMap.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts/MapInteractionHandlerSelector.cs
  DirectionAR/Assets/Scripts/2DMap/Scripts/MapInteractionHandlerSelector.cs.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts/MapStyleChangedHandler.cs
  DirectionAR/Assets/Scripts/2DMap/Scripts/MapStyleChangedHandler.cs.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts/OrthoCameraMapDimensionSynchronizer.cs
  DirectionAR/Assets/Scripts/2DMap/Scripts/OrthoCameraMapDimensionSynchronizer.cs.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts/SearchHandler.cs
  DirectionAR/Assets/Scripts/2DMap/Scripts/SearchHandler.cs.meta
  DirectionAR/Assets/Scripts/2DMap/Scripts/ZoomButtonHandler.cs
  DirectionAR/Assets/Scripts/2DMap/Scripts/ZoomButtonHandler.cs.meta
  DirectionAR/Assets/Scripts/Gps.meta
  DirectionAR/Assets/Scripts/Manager/MapPinManager.cs
  DirectionAR/Assets/Scripts/Manager/MapPinManager.cs.meta
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_FooterButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_MainButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_NavigationBackButton.cs
  DirectionAR/Assets/Scripts/UI/ButtonMapping/UI_NavigationBackButton.cs.meta
  DirectionAR/Assets/Scripts/Utils/Define.cs
  DirectionAR/Assets/Scripts/Utils/Places.cs
  DirectionAR/Assets/Scripts/Utils/Places.cs.meta
  DirectionAR/Packages/manifest.json
  DirectionAR/Packages/packages-lock.json
  DirectionAR/ProjectSettings/AndroidResolverDependencies.xml
  DirectionAR/ProjectSettings/EditorBuildSettings.asset
  DirectionAR/ProjectSettings/PackageManagerSettings.asset
Labels: enhancement
